name: GitHub Pages Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Tailwind CSS CLI
        run: npm install -g tailwindcss@latest

      - name: Build Tailwind CSS
        run: |
          tailwindcss -i ./css/input.css -o ./public/css/tailwind.css && tailwindcss -i ./css/input.css -o ./public/css/tailwind.min.css --minify
    
      - name: Upload CSS as artifact
        uses: actions/upload-artifact@v4
        with:
          name: css-files
          path: | 
            public/css/**

      - name: Create page artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/css/**
          git commit -m "Automatic Build Tailwind CSS" -a || echo "No changes to commit"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4